import { ProviderDefinition } from '../core/types';

export const cloudflareProvider: ProviderDefinition = {
  id: 'cloudflare',
  name: 'Cloudflare Workers AI',
  models: [
    {
      id: 'cloudflare/@cf/openai/gpt-oss-120b',
      modelId: '@cf/openai/gpt-oss-120b',
      name: 'GPT OSS 120B',
      provider: 'cloudflare',
      category: 'text',
      inputModalities: ['text'],
      outputModalities: ['text'],
      priority: 78,
      enabled: true,
      maxInputTokens: 128000,
      maxOutputTokens: 8192,
      supportsTools: true,
      free: true,
      freeReason: 'provider daily free allocation',
      tags: ['cloudflare', 'workers-ai', 'free'],
    },
    {
      id: 'cloudflare/@cf/openai/gpt-oss-20b',
      modelId: '@cf/openai/gpt-oss-20b',
      name: 'GPT OSS 20B',
      provider: 'cloudflare',
      category: 'text',
      inputModalities: ['text'],
      outputModalities: ['text'],
      priority: 78,
      enabled: true,
      maxInputTokens: 128000,
      maxOutputTokens: 8192,
      supportsTools: true,
      free: true,
      freeReason: 'provider daily free allocation',
      tags: ['cloudflare', 'workers-ai', 'free'],
    },
    {
      id: 'cloudflare/@cf/meta/llama-3.1-8b-instruct',
      modelId: '@cf/meta/llama-3.1-8b-instruct',
      name: 'Llama 3.1 8B Instruct',
      provider: 'cloudflare',
      category: 'text',
      inputModalities: ['text'],
      outputModalities: ['text'],
      priority: 78,
      enabled: true,
      maxInputTokens: 128000,
      maxOutputTokens: 8192,
      supportsTools: true,
      free: true,
      freeReason: 'provider daily free allocation',
      tags: ['cloudflare', 'workers-ai', 'llama', 'free'],
    },
    {
      id: 'cloudflare/@cf/meta/llama-3.2-3b-instruct',
      modelId: '@cf/meta/llama-3.2-3b-instruct',
      name: 'Llama 3.2 3B Instruct',
      provider: 'cloudflare',
      category: 'text',
      inputModalities: ['text'],
      outputModalities: ['text'],
      priority: 78,
      enabled: true,
      maxInputTokens: 128000,
      maxOutputTokens: 8192,
      supportsTools: true,
      free: true,
      freeReason: 'provider daily free allocation',
      tags: ['cloudflare', 'workers-ai', 'llama', 'free'],
    },
    {
      id: 'cloudflare/@cf/black-forest-labs/flux-1-schnell',
      modelId: '@cf/black-forest-labs/flux-1-schnell',
      name: 'FLUX.1 Schnell',
      provider: 'cloudflare',
      category: 'image',
      inputModalities: ['text'],
      outputModalities: ['image'],
      priority: 78,
      enabled: true,
      maxInputTokens: 2048,
      maxOutputTokens: 0,
      supportsTools: false,
      free: true,
      freeReason: 'provider daily free allocation',
      tags: ['cloudflare', 'workers-ai', 'image', 'flux', 'free'],
    },
    {
      id: 'cloudflare/@cf/bytedance/stable-diffusion-xl-lightning',
      modelId: '@cf/bytedance/stable-diffusion-xl-lightning',
      name: 'Stable Diffusion XL Lightning',
      provider: 'cloudflare',
      category: 'image',
      inputModalities: ['text'],
      outputModalities: ['image'],
      priority: 77,
      enabled: true,
      maxInputTokens: 2048,
      maxOutputTokens: 0,
      supportsTools: false,
      free: true,
      freeReason: 'provider daily free allocation',
      tags: ['cloudflare', 'workers-ai', 'image', 'sdxl', 'free'],
    },
    {
      id: 'cloudflare/@cf/stabilityai/stable-diffusion-xl-base-1.0',
      modelId: '@cf/stabilityai/stable-diffusion-xl-base-1.0',
      name: 'Stable Diffusion XL Base',
      provider: 'cloudflare',
      category: 'image',
      inputModalities: ['text'],
      outputModalities: ['image'],
      priority: 76,
      enabled: true,
      maxInputTokens: 2048,
      maxOutputTokens: 0,
      supportsTools: false,
      free: true,
      freeReason: 'provider daily free allocation',
      tags: ['cloudflare', 'workers-ai', 'image', 'sdxl', 'free'],
    },
    {
      id: 'cloudflare/@cf/llava-hf/llava-1.5-7b-hf',
      modelId: '@cf/llava-hf/llava-1.5-7b-hf',
      name: 'LLaVA 1.5 7B HF',
      provider: 'cloudflare',
      category: 'vision',
      inputModalities: ['image', 'text'],
      outputModalities: ['text'],
      priority: 78,
      enabled: true,
      maxInputTokens: 4096,
      maxOutputTokens: 512,
      supportsTools: false,
      free: true,
      freeReason: 'provider daily free allocation',
      tags: ['cloudflare', 'workers-ai', 'image-to-text', 'vision', 'free'],
    },
    {
      id: 'cloudflare/@cf/unum/uform-gen2-qwen-500m',
      modelId: '@cf/unum/uform-gen2-qwen-500m',
      name: 'UForm Gen2 Qwen 500M',
      provider: 'cloudflare',
      category: 'vision',
      inputModalities: ['image', 'text'],
      outputModalities: ['text'],
      priority: 77,
      enabled: true,
      maxInputTokens: 4096,
      maxOutputTokens: 512,
      supportsTools: false,
      free: true,
      freeReason: 'provider daily free allocation',
      tags: ['cloudflare', 'workers-ai', 'image-to-text', 'vision', 'free'],
    },
    {
      id: 'cloudflare/@cf/myshell-ai/melotts',
      modelId: '@cf/myshell-ai/melotts',
      name: 'MeloTTS',
      provider: 'cloudflare',
      category: 'audio',
      inputModalities: ['text'],
      outputModalities: ['audio'],
      priority: 78,
      enabled: true,
      maxInputTokens: 4096,
      maxOutputTokens: 0,
      supportsTools: false,
      free: true,
      freeReason: 'provider daily free allocation',
      tags: ['cloudflare', 'workers-ai', 'text-to-speech', 'tts', 'free'],
    },
    {
      id: 'cloudflare/@cf/deepgram/aura-1',
      modelId: '@cf/deepgram/aura-1',
      name: 'Deepgram Aura 1',
      provider: 'cloudflare',
      category: 'audio',
      inputModalities: ['text'],
      outputModalities: ['audio'],
      priority: 77,
      enabled: true,
      maxInputTokens: 4096,
      maxOutputTokens: 0,
      supportsTools: false,
      free: true,
      freeReason: 'provider daily free allocation',
      tags: ['cloudflare', 'workers-ai', 'text-to-speech', 'deepgram', 'free'],
    },
    {
      id: 'cloudflare/@cf/deepgram/aura-2-en',
      modelId: '@cf/deepgram/aura-2-en',
      name: 'Deepgram Aura 2 English',
      provider: 'cloudflare',
      category: 'audio',
      inputModalities: ['text'],
      outputModalities: ['audio'],
      priority: 77,
      enabled: true,
      maxInputTokens: 4096,
      maxOutputTokens: 0,
      supportsTools: false,
      free: true,
      freeReason: 'provider daily free allocation',
      tags: ['cloudflare', 'workers-ai', 'text-to-speech', 'deepgram', 'free'],
    },
    {
      id: 'cloudflare/@cf/deepgram/aura-2-es',
      modelId: '@cf/deepgram/aura-2-es',
      name: 'Deepgram Aura 2 Spanish',
      provider: 'cloudflare',
      category: 'audio',
      inputModalities: ['text'],
      outputModalities: ['audio'],
      priority: 77,
      enabled: true,
      maxInputTokens: 4096,
      maxOutputTokens: 0,
      supportsTools: false,
      free: true,
      freeReason: 'provider daily free allocation',
      tags: ['cloudflare', 'workers-ai', 'text-to-speech', 'deepgram', 'free'],
    },
  ],
};
