import { ProviderDefinition, ProviderModel } from '../core/types';

const models: ProviderModel[] = [
  {
    id: 'cohere/command-a-03-2025',
    modelId: 'command-a-03-2025',
    name: 'Command A 03-2025',
    description: 'Cohere Command A chat model for agents, tool use, RAG, and multilingual workloads.',
    provider: 'cohere',
    category: 'text',
    inputModalities: ['text'],
    outputModalities: ['text'],
    priority: 76,
    enabled: true,
    maxInputTokens: 256000,
    maxOutputTokens: 8192,
    supportsTools: true,
    supportsReasoning: false,
    free: true,
    freeReason: 'provider free-tier pool',
    tags: ['cohere', 'command', 'chat', 'tools', 'free'],
  },
  {
    id: 'cohere/command-r7b-12-2024',
    modelId: 'command-r7b-12-2024',
    name: 'Command R7B 12-2024',
    description: 'Small Cohere Command R chat model for RAG, agents, and tool use.',
    provider: 'cohere',
    category: 'text',
    inputModalities: ['text'],
    outputModalities: ['text'],
    priority: 75,
    enabled: true,
    maxInputTokens: 128000,
    maxOutputTokens: 4096,
    supportsTools: true,
    supportsReasoning: false,
    free: true,
    freeReason: 'provider free-tier pool',
    tags: ['cohere', 'command', 'chat', 'tools', 'free'],
  },
  {
    id: 'cohere/c4ai-aya-vision-32b',
    modelId: 'c4ai-aya-vision-32b',
    name: 'C4AI Aya Vision 32B',
    description: 'Cohere Aya Vision multimodal chat model for image and text inputs.',
    provider: 'cohere',
    category: 'vision',
    inputModalities: ['image', 'text'],
    outputModalities: ['text'],
    priority: 75,
    enabled: true,
    maxInputTokens: 128000,
    maxOutputTokens: 4096,
    supportsTools: false,
    supportsReasoning: false,
    free: true,
    freeReason: 'provider free-tier pool',
    tags: ['cohere', 'aya', 'vision', 'chat', 'free'],
  },
];

export const cohereProvider: ProviderDefinition = {
  id: 'cohere',
  name: 'Cohere',
  models,
};
