import { ProviderDefinition } from '../core/types';

export const mistralProvider: ProviderDefinition = {
  id: 'mistral',
  name: 'Mistral AI',
  models: [
    {
      id: 'mistral/mistral-large-latest',
      modelId: 'mistral-large-latest',
      name: 'Mistral Large',
      provider: 'mistral',
      priority: 75,
      enabled: true,
      maxInputTokens: 128000,
      maxOutputTokens: 8192,
      supportsTools: true,
      free: true,
      freeReason: 'provider free-tier pool',
      tags: ['mistral', 'large', 'tools'],
    },
    {
      id: 'mistral/mistral-small-latest',
      modelId: 'mistral-small-latest',
      name: 'Mistral Small',
      provider: 'mistral',
      priority: 55,
      enabled: true,
      maxInputTokens: 32000,
      maxOutputTokens: 4096,
      supportsTools: true,
      free: true,
      freeReason: 'provider free-tier pool',
      tags: ['mistral', 'small', 'fast'],
    },
    {
      id: 'mistral/voxtral-mini-tts-2603',
      modelId: 'voxtral-mini-tts-2603',
      name: 'Voxtral Mini TTS',
      provider: 'mistral',
      category: 'audio',
      inputModalities: ['text'],
      outputModalities: ['audio'],
      priority: 74,
      enabled: true,
      maxInputTokens: 4096,
      maxOutputTokens: 0,
      supportsTools: false,
      free: true,
      freeReason: 'provider free-tier pool',
      tags: ['mistral', 'voxtral', 'text-to-speech', 'tts'],
    },
  ],
};
