import { ProviderDefinition } from '../core/types';

export const nvidiaProvider: ProviderDefinition = {
  id: 'nvidia',
  name: 'NVIDIA',
  models: [
    {
      id: 'nvidia/nemotron-3-super-120b-a12b',
      modelId: 'nvidia/nemotron-3-super-120b-a12b',
      name: 'Nemotron 3 Super 120B A12B',
      provider: 'nvidia',
      category: 'text',
      inputModalities: ['text'],
      outputModalities: ['text'],
      priority: 80,
      enabled: true,
      maxInputTokens: 128000,
      maxOutputTokens: 8192,
      supportsTools: true,
      supportsReasoning: true,
      free: true,
      freeReason: 'provider free-tier pool',
      tags: ['nvidia', 'nemotron', 'reasoning'],
    },
    {
      id: 'nvidia/black-forest-labs/flux.1-schnell',
      modelId: 'black-forest-labs/flux.1-schnell',
      name: 'FLUX.1 Schnell',
      provider: 'nvidia',
      category: 'image',
      inputModalities: ['text'],
      outputModalities: ['image'],
      priority: 79,
      enabled: true,
      maxInputTokens: 2048,
      maxOutputTokens: 0,
      supportsTools: false,
      free: true,
      freeReason: 'NVIDIA visual genai endpoint verified',
      tags: ['nvidia', 'image', 'flux', 'visual-genai'],
    },
    {
      id: 'nvidia/black-forest-labs/flux.1-dev',
      modelId: 'black-forest-labs/flux.1-dev',
      name: 'FLUX.1 Dev',
      provider: 'nvidia',
      category: 'image',
      inputModalities: ['text'],
      outputModalities: ['image'],
      priority: 78,
      enabled: true,
      maxInputTokens: 2048,
      maxOutputTokens: 0,
      supportsTools: false,
      free: true,
      freeReason: 'NVIDIA visual genai endpoint catalog',
      tags: ['nvidia', 'image', 'flux', 'visual-genai'],
    },
    {
      id: 'nvidia/black-forest-labs/flux.2-klein-4b',
      modelId: 'black-forest-labs/flux.2-klein-4b',
      name: 'FLUX.2 Klein 4B',
      provider: 'nvidia',
      category: 'image',
      inputModalities: ['text', 'image'],
      outputModalities: ['image'],
      priority: 78,
      enabled: true,
      maxInputTokens: 2048,
      maxOutputTokens: 0,
      supportsTools: false,
      free: true,
      freeReason: 'NVIDIA visual genai endpoint catalog',
      tags: ['nvidia', 'image', 'flux', 'visual-genai'],
    },
    {
      id: 'nvidia/black-forest-labs/flux.1-kontext-dev',
      modelId: 'black-forest-labs/flux.1-kontext-dev',
      name: 'FLUX.1 Kontext Dev',
      provider: 'nvidia',
      category: 'image',
      inputModalities: ['text', 'image'],
      outputModalities: ['image'],
      priority: 77,
      enabled: true,
      maxInputTokens: 2048,
      maxOutputTokens: 0,
      supportsTools: false,
      free: true,
      freeReason: 'NVIDIA visual genai endpoint catalog',
      tags: ['nvidia', 'image', 'flux', 'visual-genai'],
    },
  ],
};
