import { ProviderDefinition } from '../core/types';

export const zaiProvider: ProviderDefinition = {
  id: 'zai',
  name: 'Z.AI',
  models: [
    {
      id: 'zai/glm-4.7-flash',
      modelId: 'glm-4.7-flash',
      name: 'GLM 4.7 Flash',
      provider: 'zai',
      category: 'text',
      inputModalities: ['text'],
      outputModalities: ['text'],
      priority: 74,
      enabled: true,
      maxInputTokens: 200000,
      maxOutputTokens: 128000,
      supportsTools: true,
      supportsReasoning: true,
      free: true,
      freeReason: 'official free model',
      tags: ['zai', 'glm', 'text', 'free'],
    },
    {
      id: 'zai/glm-4.5-flash',
      modelId: 'glm-4.5-flash',
      name: 'GLM 4.5 Flash',
      provider: 'zai',
      category: 'text',
      inputModalities: ['text'],
      outputModalities: ['text'],
      priority: 73,
      enabled: true,
      maxInputTokens: 200000,
      maxOutputTokens: 98304,
      supportsTools: true,
      supportsReasoning: true,
      free: true,
      freeReason: 'official free model',
      tags: ['zai', 'glm', 'text', 'free'],
    },
    {
      id: 'zai/glm-4.6v-flash',
      modelId: 'glm-4.6v-flash',
      name: 'GLM 4.6V Flash',
      provider: 'zai',
      category: 'vision',
      inputModalities: ['image', 'text'],
      outputModalities: ['text'],
      priority: 73,
      enabled: true,
      maxInputTokens: 128000,
      maxOutputTokens: 32768,
      supportsTools: false,
      free: true,
      freeReason: 'official free model',
      tags: ['zai', 'glm', 'vision', 'image-to-text', 'free'],
    },
  ],
};
